[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/assets/img/generated", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
  ]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"
