[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/assets/img/generated", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
  ]

[build.environment]
  NODE_VERSION = "lts/*"

[[redirects]]
  from = "https://www.bobmonsour.com/posts/11ty-bundler-1/"
  to = "https://www.bobmonsour.com/posts/11ty-bundle-1/"
  status = 301

[[redirects]]
  from = "https://www.bobmonsour.com/posts/11ty-bundler-2/"
  to = "https://www.bobmonsour.com/posts/11ty-bundle-2/"
  status = 301
