[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/assets/img/generated", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
  ]

[build.environment]
  NODE_VERSION = "lts/*"

[[redirects]]
  from = "https://www.bobmonsour.com/posts/11ty-bundler-1/"
  to = "https://www.bobmonsour.com/posts/11ty-bundle-1/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bobmonsour.com/posts/11ty-bundler-2/"
  to = "https://www.bobmonsour.com/posts/11ty-bundle-2/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bobmonsour.com/posts/the-evolution-of-my-CSS-pipeline-in-eleventy/"
  to = "https://www.bobmonsour.com/posts/the-evolution-of-my-CSS-pipeline-in-eleventy-part-1/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bobmonsour.com/pages/archive/"
  to = "https://www.bobmonsour.com/archive/"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bobmonsour.com/posts/11ty-bundle-4/"
  to = "https://www.bobmonsour.com/posts/11ty-bundle-1-4/"
  status = 301

[[redirects]]
  from = "https://www.bobmonsour.com/posts/11ty-bundle-3/"
  to = "https://www.bobmonsour.com/posts/11ty-bundle-1-4/"
  status = 301

[[redirects]]
  from = "https://www.bobmonsour.com/posts/11ty-bundle-3/"
  to = "https://www.bobmonsour.com/posts/11ty-bundle-1-4/"
  status = 301

[[redirects]]
  from = "https://www.bobmonsour.com/posts/11ty-bundle-1/"
  to = "https://www.bobmonsour.com/posts/11ty-bundle-1-4/"
  status = 301
