[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [
    "_site/assets/img/generated", # Eleventy Image Disk Cache
    ".cache" # Remote Asset Cache
  ]

[build.environment]
  NODE_VERSION = "lts/*"
