name: Scheduled build
on:
  schedule:
    - cron: '0 */8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger our build webhook on Netlify
        env:
          TOKEN: ${{ secrets.WEBMENTION_BUILD }}
        run: curl -X POST -d {} ${TOKEN}
